version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - db_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=root  # 設置 Grafana 管理員帳號
      - GF_SECURITY_ADMIN_PASSWORD=admin  # 設置 Grafana 管理員密碼
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel  # 安裝常用插件
    ports:
      - "3000:3000"
    restart: always
    networks:
      - db_network
    volumes:
      - grafana_data:/var/lib/grafana  # Grafana 數據存儲卷

networks:
  db_network:

volumes:
  grafana_data: {}
  prometheus_data: {}
  