global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  # Monitor NETdata
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['host.docker.internal:19999']